language: php
php:
  - 5.6
  - 5.5
  - nightly
  - hhvm
matrix:
  allow_failures:
    - php:
      - nightly
install:
  - composer install --prefer-dist
after_script:
  - travis-ocular.sh Maslosoft\Gazebo
script:
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "hhvm" ] || [ "$TRAVIS_PHP_VERSION" == "nightly" ]; then vendor/bin/codecept run unit; fi;'
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ] && [ "$TRAVIS_PHP_VERSION" != "nightly" ]; then vendor/bin/codecept run unit --coverage --html --coverage-html=. --coverage-xml=./coverage.clover; fi;'