language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - nightly
  - hhvm
matrix:
  allow_failures:
    - php: nightly
cache:
  directories:
    - vendor
install:
  - composer install --dev --prefer-dist --no-interaction
  # Get fresh tests
  - rm -rf vendor/maslosoft/gazebotest
  - git clone https://github.com/Maslosoft/GazeboTest.git vendor/maslosoft/gazebotest
before_script:
  - cd $TRAVIS_BUILD_DIR
script:
  - bash run-travis
