language: php
php:
  - 7.4
  - 8.0
  - 8.1
  - nightly
  - hhvm
matrix:
  allow_failures:
    - php: nightly
cache:
  directories:
    - vendor
install:
  - composer install --dev --prefer-dist --no-interaction
before_script:
  - cd $TRAVIS_BUILD_DIR
script:
  - bash run-travis
